# new API
POST https://translate.api.cloud.yandex.net/translate/v2/translate
Authorization: Api-Key {{api_key}}
Content-Type: application/json

{
  "folderId": "{{folder_id}}",
  "texts": ["Hello", "World"],
  "targetLanguageCode": "ru"
}

### old API
POST https://translate.yandex.net/api/v1.5/tr.json/translate
 ?key={{old_token}}
 &text=Hello
 &lang=ru
 &format=plain


### get all languages
POST https://translate.api.cloud.yandex.net/translate/v2/languages
Authorization: Api-Key {{api_key}}
Content-Type: application/json

{}

### github create releases
POST https://api.github.com/repos/skar404/alfred-translate/releases
Authorization: Bearer {{github_token}}
Content-Type: application/json

{"tag_name":"test_github_api_2"}

### github upload assets
POST https://uploads.github.com/repos/skar404/alfred-translate/releases/49412475/assets?name=Makefile.zip
Authorization: Bearer {{github_token}}
Content-Type: application/zip

< ../Makefile.zip
###
